import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = resolve(__dirname, "../src/data/ranking.json");
const outputPath = resolve(__dirname, "../public/sitemap.xml");

const BASE = "https://www.llmcompare.cc";
const today = new Date().toISOString().slice(0, 10);

const models = JSON.parse(readFileSync(dataPath, "utf-8"));

const staticPages = [
  { loc: `${BASE}/`, lastmod: today, priority: "1.0" },
  { loc: `${BASE}/models`, lastmod: today, priority: "0.9" },
  { loc: `${BASE}/compare`, lastmod: today, priority: "0.6" },
  { loc: `${BASE}/about`, lastmod: today, priority: "0.5" },
  { loc: `${BASE}/favorites`, lastmod: today, priority: "0.3" },
];

const productPages = models.map((m) => ({
  loc: `${BASE}/models/${m.id}`,
  lastmod: m.meta?.release_date || today,
  priority: m.flags?.frontier ? "0.8" : "0.6",
}));

const all = [...staticPages, ...productPages];

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  "<!-- Auto-generated by scripts/generate-sitemap.mjs, do not edit -->",
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...all.map(
    ({ loc, lastmod, priority }) =>
      `  <url><loc>${loc}</loc><lastmod>${lastmod}</lastmod><priority>${priority}</priority></url>`,
  ),
  "</urlset>",
  "",
].join("\n");

writeFileSync(outputPath, xml);
console.log(`Sitemap written: ${all.length} URLs`);
